### ISSUE TITLE
Cannot Update the lessons.... Issue with Lab & Terminal

### ISSUE THREAD

**Issue by edisplay** [learn-co-curriculum/first-lab-ruby-learn-cli-osx#32]
Please see the screenshots below... the issue is with learn commands 
Maybe the gem install learn-co ?

I managed to complete the assignment but it won't update since I completed it without the learn commands. I used rspec --format doc command to test and confirm solution; and, used git commands git add . along with git commit -am and git push to push to git. 

Commits found here: 
https://github.com/edisplay/first-lab-ruby-learn-cli-osx-intro-to-learn/commits/master

Pls. help and Thanks in advance ....

![used rspec and pushed with git commands](https://cloud.githubusercontent.com/assets/1013570/15918678/4fb6ac42-2dd7-11e6-9aa4-ec9f82aaabdb.png)
![cannot test with learn](https://cloud.githubusercontent.com/assets/1013570/15918679/4fb78c3e-2dd7-11e6-93b4-41b37bcc20c8.png)

**Comment by edisplay** [comment]
rvm list
![rvm list](https://cloud.githubusercontent.com/assets/1013570/15918864/7f5fe3c6-2dd9-11e6-9172-458cd0bc1ff3.png)

**Comment by edisplay** [comment]
Cannot complete/update assignment. Pls. Help. More info. here: https://github.com/learn-co-curriculum/first-lab-ruby-learn-cli-osx/issues/32

JAKEBRADY5 SAID A DAY AGO
Hi Francisco

JAKEBRADY5 SAID A DAY AGO
Thanks for posting those screenshots!

JAKEBRADY5 SAID A DAY AGO
I've got a way to fix that

JAKEBRADY5 SAID A DAY AGO
could you type rvm list and copy me the results?

EDISPLAY SAID A DAY AGO
Sure!

EDISPLAY SAID A DAY AGO

# => - current # =\* - current && default # \* - default

<img src="https://s3.amazonaws.com/flatironschool-uploads/5791bfce-6110-4c67-8f7f-fb021d25a46c.png" alt="">

JAKEBRADY5 SAID A DAY AGO
ah yes ok

JAKEBRADY5 SAID A DAY AGO
rvm install 2.2.3 please

JAKEBRADY5 SAID A DAY AGO
and when that completes do rvm use 2.2.3 --default

JAKEBRADY5 SAID A DAY AGO
one more command after that, so let me know if those work

EDISPLAY SAID A DAY AGO
<img src="https://s3.amazonaws.com/flatironschool-uploads/ad54e69f-c1b2-41e2-8bfc-8ac4d0be577d.png" alt="">
<img src="https://s3.amazonaws.com/flatironschool-uploads/9b8a900e-fefa-4bc6-85f8-caa657c65fe1.png" alt="">

EDISPLAY SAID A DAY AGO
ok those commands are installed  :smile:

EDISPLAY SAID A DAY AGO
<img src="https://s3.amazonaws.com/flatironschool-uploads/94c6a66f-708f-41aa-b574-fb0e7c544c45.png" alt="">

EDISPLAY SAID A DAY AGO
the image above has the learn commands

JAKEBRADY5 SAID A DAY AGO
yep, try gem install learn-co
EDISPLAY SAID A DAY AGO
It's installing now! :smile:

EDISPLAY SAID A DAY AGO
it installed!

EDISPLAY SAID 
<img src="https://s3.amazonaws.com/flatironschool-uploads/dc5ba476-64e8-4219-89a5-55876b268166.png" alt="">

EDISPLAY SAID A DAY AGO
Typed learn commands again!

JAKEBRADY5 SAID A DAY AGO
learn command not doing anything now?
EDISPLAY SAID A DAY AGO
Yes!

EDISPLAY SAID A DAY AGO
Should I also install again this gem install bundler?

EDISPLAY SAID A DAY AGO
Got it working !!!! :grinning:

EDISPLAY SAID A DAY AGO
I installed: gem install bundler and then it asked me to install: bundle install ... and it worked on terminal

EDISPLAY SAID A DAY AGO
<img src="https://s3.amazonaws.com/flatironschool-uploads/6ad8b108-a4ea-4d82-9600-9674e69ab218.png" alt="">

<img src="https://s3.amazonaws.com/flatironschool-uploads/26e0d0e3-c6d4-4ed7-a0f6-273b556aa900.png" alt="">

EDISPLAY SAID A DAY AGO
Thank you very, very much! :thumbsup:

**Comment by edisplay** [comment]
THE ABOVE FIXED THE ISSUE BUT OTHER INDIVIDUAL PROJECTS MAY STILL HAVE A PROBLEM. IF THE FILES AREN'T PROPERLY SET-UP ON OTHER PROJECTS TRY THE FOLLOWING! ...

learn
rvm list
rvm get stable --auto-dotfiles
gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
rvm list
rvm get stable --auto-dotfiles
learn

======================== FOR EXAMPLE: ==== MY TERMINAL OUTPUT ... =====
[08:58:22](master) first-lab-001-prework-ios
// ♥ learn
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require': /Users/edisplay/.rvm/gems/ruby-2.2.3/gems/learn-co-3.5.4/lib/learn/options_sanitizer.rb:123: syntax error, unexpected ',' (SyntaxError)
    def rebuild_args!(flag_arg:, add_test_command:)
                                ^
/Users/edisplay/.rvm/gems/ruby-2.2.3/gems/learn-co-3.5.4/lib/learn/options_sanitizer.rb:221: syntax error, unexpected keyword_end, expecting end-of-input
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in`require'
    from /Users/edisplay/.rvm/gems/ruby-2.2.3/gems/learn-co-3.5.4/lib/learn.rb:7:in `<top (required)>'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in`require'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
    from /Users/edisplay/.rvm/gems/ruby-2.2.3/gems/learn-co-3.5.4/bin/learn:3:in`<top (required)>'
    from /Users/edisplay/.rvm/gems/ruby-2.2.3/bin/learn:23:in `load'
    from /Users/edisplay/.rvm/gems/ruby-2.2.3/bin/learn:23:in`<main>'
    from /Users/edisplay/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `eval'
    from /Users/edisplay/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in`<main>'
[09:01:15](master) first-lab-001-prework-ios
// ♥ rvm list
Warning! PATH is not properly set up, '/Users/edisplay/.rvm/gems/ruby-2.2.3/bin' is not at first place,
         usually this is caused by shell initialization files - check them for 'PATH=...' entries,
         it might also help to re-add RVM to your dotfiles: 'rvm get stable --auto-dotfiles',
         to fix temporarily in this shell session run: 'rvm use ruby-2.2.3'.

rvm rubies

=\* ruby-2.2.3 [ x86_64 ]
   ruby-2.3.0 [ x86_64 ]

# => - current

# =\* - current && default

# \* - default

[09:18:13](master) first-lab-001-prework-ios
// ♥ rvm get stable --auto-dotfiles
Warning! PATH is not properly set up, '/Users/edisplay/.rvm/gems/ruby-2.2.3/bin' is not at first place,
         usually this is caused by shell initialization files - check them for 'PATH=...' entries,
         it might also help to re-add RVM to your dotfiles: 'rvm get stable --auto-dotfiles',
         to fix temporarily in this shell session run: 'rvm use ruby-2.2.3'.
Downloading https://get.rvm.io
Downloading https://raw.githubusercontent.com/wayneeseguin/rvm/master/binscripts/rvm-installer.asc
Verifying /Users/edisplay/.rvm/archives/rvm-installer.asc
gpg: directory `/Users/edisplay/.gnupg' created
gpg: new configuration file`/Users/edisplay/.gnupg/gpg.conf' created
gpg: WARNING: options in `/Users/edisplay/.gnupg/gpg.conf' are not yet active during this run
gpg: keyring`/Users/edisplay/.gnupg/pubring.gpg' created
gpg: Signature made Thu Jan 21 14:38:21 2016 EST using RSA key ID BF04FF17
gpg: Can't check signature: public key not found
Warning, RVM 1.26.0 introduces signed releases and automated check of signatures when GPG software found.
Assuming you trust Michal Papis import the mpapis public key (downloading the signatures).

GPG signature verification failed for '/Users/edisplay/.rvm/archives/rvm-installer' - 'https://raw.githubusercontent.com/wayneeseguin/rvm/master/binscripts/rvm-installer.asc'!
try downloading the signatures:

```
gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
```

or if it fails:

```
command curl -sSL https://rvm.io/mpapis.asc | gpg --import -
```

the key can be compared with:

```
https://rvm.io/mpapis.asc
https://keybase.io/mpapis
```

-bash: return: _ret: numeric argument required
[09:19:08](master) first-lab-001-prework-ios
// ♥ gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
gpg: keyring `/Users/edisplay/.gnupg/secring.gpg' created
gpg: requesting key D39DC0E3 from hkp server keys.gnupg.net
gpg: /Users/edisplay/.gnupg/trustdb.gpg: trustdb created
gpg: key D39DC0E3: public key "Michal Papis (RVM signing) mpapis@gmail.com" imported
gpg: no ultimately trusted keys found
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
[09:20:23](master) first-lab-001-prework-ios
// ♥ rvm list
Warning! PATH is not properly set up, '/Users/edisplay/.rvm/gems/ruby-2.2.3/bin' is not at first place,
         usually this is caused by shell initialization files - check them for 'PATH=...' entries,
         it might also help to re-add RVM to your dotfiles: 'rvm get stable --auto-dotfiles',
         to fix temporarily in this shell session run: 'rvm use ruby-2.2.3'.

rvm rubies

=\* ruby-2.2.3 [ x86_64 ]
   ruby-2.3.0 [ x86_64 ]

# => - current

# =\* - current && default

# \* - default

[09:20:29](master) first-lab-001-prework-ios
// ♥ rvm get stable --auto-dotfiles
Warning! PATH is not properly set up, '/Users/edisplay/.rvm/gems/ruby-2.2.3/bin' is not at first place,
         usually this is caused by shell initialization files - check them for 'PATH=...' entries,
         it might also help to re-add RVM to your dotfiles: 'rvm get stable --auto-dotfiles',
         to fix temporarily in this shell session run: 'rvm use ruby-2.2.3'.
Downloading https://get.rvm.io
Downloading https://raw.githubusercontent.com/wayneeseguin/rvm/master/binscripts/rvm-installer.asc
Verifying /Users/edisplay/.rvm/archives/rvm-installer.asc
gpg: Signature made Thu Jan 21 14:38:21 2016 EST using RSA key ID BF04FF17
gpg: Good signature from "Michal Papis (RVM signing) mpapis@gmail.com"
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 409B 6B17 96C2 7546 2A17  0311 3804 BB82 D39D C0E3
     Subkey fingerprint: 62C9 E5F4 DA30 0D94 AC36  166B E206 C29F BF04 FF17
GPG verified '/Users/edisplay/.rvm/archives/rvm-installer'
Turning on auto dotfiles mode.
Downloading https://github.com/rvm/rvm/archive/1.27.0.tar.gz
Downloading https://github.com/rvm/rvm/releases/download/1.27.0/1.27.0.tar.gz.asc
gpg: Signature made Tue Mar 29 09:49:47 2016 EDT using RSA key ID BF04FF17
gpg: Good signature from "Michal Papis (RVM signing) mpapis@gmail.com"
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 409B 6B17 96C2 7546 2A17  0311 3804 BB82 D39D C0E3
     Subkey fingerprint: 62C9 E5F4 DA30 0D94 AC36  166B E206 C29F BF04 FF17
GPG verified '/Users/edisplay/.rvm/archives/rvm-1.27.0.tgz'

Upgrading the RVM installation in /Users/edisplay/.rvm/
    Removing rvm PATH line from /Users/edisplay/.mkshrc /Users/edisplay/.profile /Users/edisplay/.bashrc.
    Adding rvm PATH line to /Users/edisplay/.profile /Users/edisplay/.mkshrc /Users/edisplay/.bashrc /Users/edisplay/.zshrc.
touch: /Users/edisplay/.zshrc: Permission denied
/Users/edisplay/.rvm/src/rvm/scripts/functions/installer: line 1102: /Users/edisplay/.zshrc: Permission denied
    Removing rvm loading line from /Users/edisplay/.profile /Users/edisplay/.bash_profile /Users/edisplay/.zlogin.
    Adding rvm loading line to /Users/edisplay/.profile /Users/edisplay/.bash_profile /Users/edisplay/.zlogin.
Upgrade of RVM in /Users/edisplay/.rvm/ is complete.

# edisplay - Francisco Cruz,

#

# Thank you for using RVM!

# We sincerely hope that RVM helps to make your life easier and more enjoyable!!!

#

# ~Wayne, Michal & team.

In case of problems: https://rvm.io/help and https://twitter.com/rvm_io

Upgrade Notes:
- No new notes to display.

RVM reloaded!
[09:20:50](master) first-lab-001-prework-ios
// ♥ rvm get stable --auto-dotfiles

[09:25:30](master) first-lab-001-prework-ios
// ♥ learn

First Lab
  added a file called "my-new-file.txt" (FAILED - 1)

Failures:

  1) First Lab added a file called "my-new-file.txt"
     Failure/Error: expect(file_added).to be_truthy

```
   expected: truthy value
        got: false
 # ./spec/lab_spec.rb:6:in `block (2 levels) in <top (required)>'
```

Finished in 0.05779 seconds (files took 0.38731 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/lab_spec.rb:4 # First Lab added a file called "my-new-file.txt"

[09:25:37](master) first-lab-001-prework-ios
// ♥
